# Generated by Django 2.2 on 2019-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email_address',
        ),
    ]
