# Generated by Django 2.2 on 2019-05-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20190508_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
