# Generated by Django 2.2 on 2019-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0005_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=50)),
                ('updated', models.CharField(max_length=50)),
            ],
        ),
    ]
