# Generated by Django 2.2 on 2019-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created',
            field=models.CharField(default='<function now at 0x10363fea0>', max_length=50),
        ),
    ]
