# Generated by Django 2.2 on 2019-05-08 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20190508_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
